#!/usr/bin/env python3
"""Generate docs/llms-full.txt — the entire documentation as one plain-markdown
file for LLM ingestion.

It walks the docs pages in navigation order, strips YAML front-matter, and
inlines any pymdownx `--8<-- "path:start:end"` snippet transclusions so the
output contains the real content (data dictionary, ERD, sources, …) rather than
the include markers. No third-party dependencies — standard library only.

Run from anywhere:  python scripts/gen_llms_full.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
OUT = DOCS / "llms-full.txt"

# Documentation pages, in reading order (mirrors mkdocs.yml `nav`).
PAGES: list[str] = [
    "index.md",
    "getting-started/index.md",
    "getting-started/quickstart.md",
    "getting-started/installation.md",
    "getting-started/concepts.md",
    "schema/index.md",
    "schema/reference-config.md",
    "schema/manifest.md",
    "schema/declaration.md",
    "schema/selectivity.md",
    "schema/accounting.md",
    "schema/transit-suspense.md",
    "schema/audit.md",
    "schema/erd.md",
    "schema/data-dictionary.md",
    "platform/index.md",
    "platform/versions.md",
    "platform/asycuda-world.md",
    "platform/xml-messages.md",
    "platform/integration.md",
    "platform/selectivity-clearance.md",
    "platform/resources.md",
    "guides/index.md",
    "guides/loading.md",
    "guides/querying.md",
    "guides/extending.md",
    "guides/worked-example.md",
    "guides/ml-risk-engine.md",
    "provenance/index.md",
    "provenance/methodology.md",
    "provenance/sources.md",
    "provenance/coverage.md",
    "provenance/fit.md",
    "skills/index.md",
]

FRONTMATTER = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
SNIPPET = re.compile(r'^--8<--\s+"([^"]+)"\s*$')


def strip_frontmatter(text: str) -> str:
    return FRONTMATTER.sub("", text, count=1)


def resolve_snippet(spec: str) -> str:
    """Resolve a snippet spec `path` or `path:start:end` (1-based, inclusive)
    against the repo root, matching pymdownx.snippets base_path=['.', 'Sydonia'].
    """
    parts = spec.split(":")
    rel, start, end = parts[0], None, None
    if len(parts) == 3:
        start, end = int(parts[1]), int(parts[2])

    for base in (REPO, REPO / "Sydonia", DOCS):
        candidate = base / rel
        if candidate.is_file():
            lines = candidate.read_text(encoding="utf-8").splitlines()
            if start is not None:
                lines = lines[start - 1 : end]
            return "\n".join(lines)
    raise FileNotFoundError(f"snippet target not found: {spec}")


def inline_snippets(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        m = SNIPPET.match(line.strip())
        out.append(resolve_snippet(m.group(1)) if m else line)
    return "\n".join(out)


def main() -> int:
    header = (
        "# Open Customs Toolbox — full documentation\n\n"
        "> Concatenation of the entire Open Customs Toolbox documentation for LLM\n"
        "> ingestion. Generated by scripts/gen_llms_full.py from the docs sources.\n"
        "> Canonical site: https://francoischastel.github.io/OpenCustomsToolbox/latest/\n"
    )
    chunks = [header]
    for rel in PAGES:
        path = DOCS / rel
        if not path.is_file():
            print(f"warning: missing page {rel}", file=sys.stderr)
            continue
        body = inline_snippets(strip_frontmatter(path.read_text(encoding="utf-8")))
        chunks.append(f"\n\n---\n\n<!-- source: docs/{rel} -->\n\n{body.strip()}\n")

    OUT.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")
    words = len(OUT.read_text(encoding="utf-8").split())
    print(f"wrote {OUT.relative_to(REPO)} — {len(PAGES)} pages, ~{words:,} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
